imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

lyra_admin:
    theme: smoothness # or ui-lightness (default)
    # additional themes installed in web/css/ui_themes
    #theme: css/ui_themes/redmond
    models:
        listing:
            class: 'Acme\ClassifiedsBundle\Entity\Listing'
#            controller: 'AcmeClassifiedsBundle:Admin'
            actions:
                publish:
                    # for batch actions it's the text displayed in drop down list
                    text: Publish
                unpublish:
                    text: Unpublish
                new:
                    # for list/object actions it's the button text
                    text: 'New listing'
                    # button icon
                    icon: circle-plus
                expired:
                    route_pattern: expired
                    text: 'Delete expired'
                    icon: trash
                    dialog:
                        title: 'Confirm delete expired'
                        message: 'Do you really want to delete all expired listings?'
            list:
                title: Listings
                columns:
                    ad_title: ~
                    published:
                        sortable: false
                    posted_at:
                        label: Date
                        format: 'j/M/Y'
                batch_actions: [publish,unpublish,delete]
                list_actions: [new,expired]
            filter:
                # search dialog title
                title: Search listings
                fields:
                    ad_title: ~
                    posted_at: ~
                    published: ~
            form:
                groups:
                    listing:
                        # panel title
                        caption: Listing
                        fields: [ad_title,ad_text]
                        # column break after this panel
                        break_after: true
                    status:
                        caption: Status
                        fields: [published,expires_at]
            services:
                # service id of user defined model manager
#                model_manager: classifieds_listing_manager